/**
 * Google Ads field catalog.
 *
 * Google's metric model differs from Meta/TikTok — Resources × Metrics ×
 * Segments via GAQL. We expose the user-friendly subset; SIS family is
 * Campaign+AdGroup-only (not at Ad level), and Quality Score is keyword-
 * level only and surfaced in Advanced.
 *
 * ~130 metrics in v22 API; ~50 curated here as featured.
 */

import type { PlatformCatalog } from "./catalog-types";

export const googleCatalog: PlatformCatalog = {
  platform: "google",
  label: "Google Ads",
  brandColor: "#4285F4",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    {
      tab: "key_metrics",
      name: "Performance",
      groups: ["Conversions", "Clicks & Impressions", "Engagement", "Phone calls"],
    },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    {
      tab: "tracking",
      name: "Conversions",
      groups: ["All conversions", "Attribution", "Per-action"],
    },
    {
      tab: "ad_settings",
      name: "Identity",
      groups: ["Names & IDs", "Status", "Schedule & status"],
    },
    { tab: "advanced", name: "Search Impression Share", groups: ["Share", "Position", "Lost"] },
    { tab: "advanced", name: "Quality", groups: ["Quality score (keyword)", "Bid estimates"] },
    { tab: "advanced", name: "Video", groups: ["TrueView"] },
    { tab: "advanced", name: "Display", groups: ["Active View"] },
    { tab: "advanced", name: "Shopping", groups: ["Product attributes"] },
    { tab: "advanced", name: "PMax", groups: ["Asset groups", "Optimization"] },
    { tab: "advanced", name: "Auction Insights", groups: ["Notes"] },
  ],
  fields: [
    // ─── Key metrics → Performance → Conversions ──────────────────────
    {
      id: "conversions",
      label: "Conversions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "conversion_value",
      label: "Conv. value",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "revenue",
      isFeatured: true,
    },
    {
      id: "cost_per_conversion",
      label: "Cost / conv.",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "value_per_conversion",
      label: "Value / conv.",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "value_per_conversion",
      agg: "weighted_avg",
      aggWeight: "conversions",
    },
    {
      id: "conversion_rate",
      label: "Conv. rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversionRate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "roas",
      label: "ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Performance → Clicks & Impressions ─────────────
    {
      id: "clicks",
      label: "Clicks",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ctr",
      label: "CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "interactions",
      label: "Interactions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "interactions",
    },
    {
      id: "interaction_rate",
      label: "Interaction rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "interaction_rate",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "spend",
      label: "Cost",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "avg_cpc",
      label: "Avg. CPC",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "avg_cpm",
      label: "Avg. CPM",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "avg_cpv",
      label: "Avg. CPV",
      hint: "TrueView",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "avg_cpv",
      invertDelta: true,
    },

    // ─── Tracking → Conversions → All conversions ──────────────────────
    {
      id: "all_conversions",
      label: "All conversions",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions",
    },
    {
      id: "all_conversions_value",
      label: "All conv. value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions_value",
    },
    {
      id: "view_through_conversions",
      label: "View-through conv.",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "view_through_conversions",
      isFeatured: true,
    },
    {
      id: "cross_device_conversions",
      label: "Cross-device conv.",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "cross_device_conversions",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "current_model_attributed_conversions",
      label: "Conv. (current model)",
      hint: "data-driven attribution",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "current_model_attributed_conversions",
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ad_group_name",
      label: "Ad group",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "campaign_channel_type",
      label: "Channel",
      hint: "Search/Display/PMax/etc",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_channel_type",
      isFeatured: true,
    },
    {
      id: "network",
      label: "Network",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "network",
    },
    {
      id: "status",
      label: "Status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },

    // ─── Advanced → Search Impression Share → Share ────────────────────
    {
      id: "search_impression_share",
      label: "Search impr. share",
      hint: "% of available auctions won",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Share",
      path: "search_impression_share",
      validLevels: ["campaign", "adset"],
      isFeatured: true,
    },
    {
      id: "search_click_share",
      label: "Click share",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Share",
      path: "search_click_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Position ─────────────────────────────────────
    {
      id: "search_top_impression_share",
      label: "Top impr. share",
      hint: "above search results",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_top_impression_share",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "search_absolute_top_impression_share",
      label: "Abs. top impr. share",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_absolute_top_impression_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Lost (the differentiator metric) ─────────────
    {
      id: "search_budget_lost_impression_share",
      label: "Search lost IS (budget)",
      hint: "% lost to budget cap",
      description:
        "High budget-lost = give the campaign more money, it can scale. Pair with Lost (Rank).",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_budget_lost_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
      isFeatured: true,
    },
    {
      id: "search_rank_lost_impression_share",
      label: "Search lost IS (rank)",
      hint: "% lost to ad rank",
      description:
        "High rank-lost = improve QS / bids / creative. DO NOT just give more money.",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_rank_lost_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
      isFeatured: true,
    },

    // ─── Advanced → Quality (keyword-level) ────────────────────────────
    {
      id: "historical_quality_score",
      label: "Quality score",
      hint: "1-10, keyword-level",
      format: "number",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_creative_quality_score",
      label: "Ad relevance",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_creative_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_landing_page_quality_score",
      label: "Landing page exp.",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_landing_page_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_search_predicted_ctr",
      label: "Expected CTR",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_search_predicted_ctr",
      validLevels: ["adset", "ad"],
    },

    // ─── Advanced → Video → TrueView ───────────────────────────────────
    {
      id: "video_views",
      label: "Video views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_views",
    },
    {
      id: "video_view_rate",
      label: "View rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_view_rate",
    },
    {
      id: "video_quartile_p25_rate",
      label: "25% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p25_rate",
    },
    {
      id: "video_quartile_p50_rate",
      label: "50% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p50_rate",
    },
    {
      id: "video_quartile_p75_rate",
      label: "75% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p75_rate",
    },
    {
      id: "video_quartile_p100_rate",
      label: "100% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p100_rate",
    },

    // ─── Advanced → Display → Active View ──────────────────────────────
    {
      id: "active_view_impressions",
      label: "Viewable impr.",
      format: "number",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_impressions",
    },
    {
      id: "active_view_viewability",
      label: "Viewability",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_viewability",
    },
    {
      id: "active_view_ctr",
      label: "Active view CTR",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_ctr",
    },
    {
      id: "active_view_cpm",
      label: "Active view CPM",
      format: "currency",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_cpm",
      invertDelta: true,
    },

    // ════════════════════════════════════════════════════════════════════
    // EXPANSION (v22 coverage) — appended fields below this line.
    // ════════════════════════════════════════════════════════════════════

    // ─── Key metrics → Performance → Conversions (expansion) ──────────
    {
      id: "all_conversions_kpi",
      label: "All conv. (incl. all types)",
      hint: "primary + secondary",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "all_conversions",
    },
    {
      id: "all_conversions_value_kpi",
      label: "All conv. value",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "all_conversions_value",
    },
    {
      id: "cross_device_conversions_value",
      label: "Cross-device conv. value",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "cross_device_conversions_value",
    },
    {
      id: "view_through_conversions_value",
      label: "View-through conv. value",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "view_through_conversions_value",
    },
    {
      id: "conversions_by_conversion_time",
      label: "Conv. (by conv. time)",
      hint: "credited to conv. day",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversions_by_conversion_time",
    },
    {
      id: "conversions_value_by_conversion_time",
      label: "Conv. value (by conv. time)",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversions_value_by_conversion_time",
    },
    {
      id: "all_conversions_by_conversion_time",
      label: "All conv. (by conv. time)",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "all_conversions_by_conversion_time",
    },
    {
      id: "conversions_by_interaction_time",
      label: "Conv. (by interaction time)",
      hint: "credited to click day",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversions_by_interaction_time",
    },

    // ─── Key metrics → Performance → Clicks & Impressions (expansion) ──
    {
      id: "engagements",
      label: "Engagements",
      hint: "Display / Discovery",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Engagement",
      path: "engagements",
    },
    {
      id: "engagement_rate",
      label: "Engagement rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Engagement",
      path: "engagement_rate",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "top_impression_percentage",
      label: "Top impr. %",
      hint: "% impr. above organic",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "top_impression_percentage",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "absolute_top_impression_percentage",
      label: "Abs. top impr. %",
      hint: "% impr. as 1st result",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "absolute_top_impression_percentage",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "search_top_impression_share_keymetric",
      label: "Search top IS",
      hint: "% top auctions won",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "search_top_impression_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Key metrics → Performance → Phone calls ──────────────────────
    {
      id: "phone_calls",
      label: "Phone calls",
      hint: "call extensions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Phone calls",
      path: "phone_calls",
    },
    {
      id: "phone_impressions",
      label: "Phone impr.",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Phone calls",
      path: "phone_impressions",
    },
    {
      id: "phone_through_rate",
      label: "PTR",
      hint: "phone-through rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Phone calls",
      path: "phone_through_rate",
      agg: "weighted_avg",
      aggWeight: "phone_impressions",
    },

    // ─── Key metrics → Cost (expansion) ───────────────────────────────
    {
      id: "cost_per_all_conversions",
      label: "Cost / all conv.",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_all_conversions",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_current_model_attributed_conversion",
      label: "Cost / conv. (current model)",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_current_model_attributed_conversion",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cross_device_conversion_cost",
      label: "Cross-device conv. cost",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cross_device_conversion_cost",
      invertDelta: true,
    },
    {
      id: "average_cost",
      label: "Avg. cost / interaction",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "average_cost",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "interactions",
    },

    // ─── Tracking → Conversions → All conversions (expansion) ─────────
    {
      id: "value_per_all_conversions",
      label: "Value / all conv.",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "value_per_all_conversions",
      agg: "weighted_avg",
      aggWeight: "all_conversions",
    },
    {
      id: "all_conversions_from_interactions_rate",
      label: "All conv. rate (interactions)",
      format: "percent",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions_from_interactions_rate",
      agg: "weighted_avg",
      aggWeight: "interactions",
    },
    {
      id: "all_conversions_from_interactions_value_per_interaction",
      label: "All conv. value / interaction",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions_from_interactions_value_per_interaction",
      agg: "weighted_avg",
      aggWeight: "interactions",
    },
    {
      id: "cost_per_all_conversions_tracking",
      label: "Cost / all conv.",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "cost_per_all_conversions",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → Attribution (expansion) ─────────────
    {
      id: "current_model_attributed_conversions_value",
      label: "Conv. value (current model)",
      hint: "data-driven attribution",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "current_model_attributed_conversions_value",
    },
    {
      id: "current_model_attributed_conversions_value_per_cost",
      label: "Conv. value / cost (current model)",
      format: "ratio",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "current_model_attributed_conversions_value_per_cost",
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "current_model_attributed_conversions_from_interactions_rate",
      label: "Conv. rate (current model)",
      format: "percent",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "current_model_attributed_conversions_from_interactions_rate",
      agg: "weighted_avg",
      aggWeight: "interactions",
    },
    {
      id: "conversion_attribution_event_type",
      label: "Attribution event type",
      hint: "click vs view",
      format: "text",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "conversion_attribution_event_type",
    },

    // ─── Tracking → Conversions → Per-action (NEW group) ──────────────
    {
      id: "segment_conversion_action",
      label: "Break out by conversion action",
      hint: "GAQL segments.conversion_action",
      description:
        "Toggle to split rows per conversion action (purchase, lead, signup). Adds segments.conversion_action to the GAQL query.",
      format: "text",
      tab: "tracking",
      category: "Conversions",
      group: "Per-action",
      path: "segments.conversion_action",
    },
    {
      id: "segment_conversion_action_name",
      label: "Conversion action name",
      format: "text",
      tab: "tracking",
      category: "Conversions",
      group: "Per-action",
      path: "segments.conversion_action_name",
    },
    {
      id: "segment_conversion_action_category",
      label: "Conversion action category",
      hint: "PURCHASE / LEAD / etc.",
      format: "text",
      tab: "tracking",
      category: "Conversions",
      group: "Per-action",
      path: "segments.conversion_action_category",
    },

    // ─── Ad settings → Identity → Names & IDs (expansion) ─────────────
    {
      id: "customer_id",
      label: "Customer ID",
      hint: "MCC / account",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "customer_id",
    },
    {
      id: "customer_name",
      label: "Customer name",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "customer_descriptive_name",
    },
    {
      id: "campaign_id",
      label: "Campaign ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_id",
      validLevels: ["campaign", "adset", "ad"],
    },
    {
      id: "ad_group_id",
      label: "Ad group ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_group_id",
      validLevels: ["adset", "ad"],
    },
    {
      id: "ad_id",
      label: "Ad ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_id",
      validLevels: ["ad"],
    },
    {
      id: "keyword_text",
      label: "Keyword",
      hint: "keyword_view only",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_group_criterion.keyword.text",
      validLevels: ["adset", "ad"],
    },
    {
      id: "keyword_match_type",
      label: "Match type",
      hint: "EXACT / PHRASE / BROAD",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_group_criterion.keyword.match_type",
      validLevels: ["adset", "ad"],
    },
    {
      id: "final_url",
      label: "Final URL",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "final_urls",
      validLevels: ["ad"],
    },
    {
      id: "display_url",
      label: "Display URL",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "display_url",
      validLevels: ["ad"],
    },
    {
      id: "path1",
      label: "Path 1",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "expanded_text_ad.path1",
      validLevels: ["ad"],
    },
    {
      id: "path2",
      label: "Path 2",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "expanded_text_ad.path2",
      validLevels: ["ad"],
    },

    // ─── Ad settings → Identity → Schedule & status (NEW group) ───────
    {
      id: "campaign_status",
      label: "Campaign status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign.status",
      validLevels: ["campaign", "adset", "ad"],
    },
    {
      id: "ad_group_status",
      label: "Ad group status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "ad_group.status",
      validLevels: ["adset", "ad"],
    },
    {
      id: "ad_status",
      label: "Ad status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "ad_group_ad.status",
      validLevels: ["ad"],
    },
    {
      id: "approval_status",
      label: "Approval status",
      hint: "APPROVED / DISAPPROVED / UNDER_REVIEW",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "ad_group_ad.policy_summary.approval_status",
      validLevels: ["ad"],
    },
    {
      id: "policy_summary",
      label: "Policy summary",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "ad_group_ad.policy_summary.review_status",
      validLevels: ["ad"],
    },
    {
      id: "bidding_strategy_type",
      label: "Bid strategy",
      hint: "tCPA, tROAS, MaxConv, etc.",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign.bidding_strategy_type",
      validLevels: ["campaign", "adset", "ad"],
    },
    {
      id: "daily_budget",
      label: "Daily budget",
      format: "currency",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign_budget.amount_micros",
      validLevels: ["campaign"],
    },
    {
      id: "total_budget",
      label: "Total budget",
      format: "currency",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign_budget.total_amount_micros",
      validLevels: ["campaign"],
    },
    {
      id: "start_date",
      label: "Start date",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign.start_date",
      validLevels: ["campaign"],
    },
    {
      id: "end_date",
      label: "End date",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign.end_date",
      validLevels: ["campaign"],
    },
    {
      id: "serving_status",
      label: "Serving status",
      hint: "SERVING / ENDED / SUSPENDED",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Schedule & status",
      path: "campaign.serving_status",
      validLevels: ["campaign", "adset", "ad"],
    },

    // ─── Advanced → SIS → Share (expansion) ───────────────────────────
    {
      id: "search_exact_match_impression_share",
      label: "Exact match IS",
      hint: "of exact-match auctions",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Share",
      path: "search_exact_match_impression_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Position (expansion) ────────────────────────
    {
      id: "search_top_impression_share_advanced",
      label: "Search top IS",
      hint: "above organic",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_top_impression_share",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "search_absolute_top_impression_share_advanced",
      label: "Search abs. top IS",
      hint: "1st position",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_absolute_top_impression_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Lost (expansion) ────────────────────────────
    {
      id: "search_budget_lost_top_impression_share",
      label: "Lost top IS (budget)",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_budget_lost_top_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
    },
    {
      id: "search_budget_lost_absolute_top_impression_share",
      label: "Lost abs. top IS (budget)",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_budget_lost_absolute_top_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
    },
    {
      id: "search_rank_lost_top_impression_share",
      label: "Lost top IS (rank)",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_rank_lost_top_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
    },
    {
      id: "search_rank_lost_absolute_top_impression_share",
      label: "Lost abs. top IS (rank)",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_rank_lost_absolute_top_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
    },

    // ─── Advanced → Quality (expansion) ───────────────────────────────
    {
      id: "quality_score",
      label: "Quality score (latest)",
      hint: "1-10, current",
      format: "number",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "first_page_cpc_bid",
      label: "First page CPC bid",
      format: "currency",
      tab: "advanced",
      category: "Quality",
      group: "Bid estimates",
      path: "ad_group_criterion.position_estimates.first_page_cpc_micros",
      validLevels: ["adset", "ad"],
    },
    {
      id: "top_of_page_cpc_bid",
      label: "Top of page CPC bid",
      format: "currency",
      tab: "advanced",
      category: "Quality",
      group: "Bid estimates",
      path: "ad_group_criterion.position_estimates.top_of_page_cpc_micros",
      validLevels: ["adset", "ad"],
    },
    {
      id: "first_position_cpc_bid",
      label: "First position CPC bid",
      format: "currency",
      tab: "advanced",
      category: "Quality",
      group: "Bid estimates",
      path: "ad_group_criterion.position_estimates.first_position_cpc_micros",
      validLevels: ["adset", "ad"],
    },

    // ─── Advanced → Video → TrueView (expansion) ──────────────────────
    {
      id: "video_view_rate_advanced",
      label: "View rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_view_rate",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "cost_per_video_view",
      label: "Cost / view",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "cost_per_video_view",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "average_cpv",
      label: "Avg. CPV",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "average_cpv",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "video_views",
    },
    {
      id: "earned_likes",
      label: "Earned likes",
      hint: "video, post-view",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_engagement_likes",
    },
    {
      id: "earned_shares",
      label: "Earned shares",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_engagement_shares",
    },
    {
      id: "earned_subscribers",
      label: "Earned subscribers",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_engagement_subscribers",
    },
    {
      id: "earned_views",
      label: "Earned views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_engagement_earned_views",
    },
    {
      id: "video_frequency",
      label: "View frequency",
      format: "ratio",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_view_frequency",
    },
    {
      id: "video_skips",
      label: "Skips",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_skips",
    },
    {
      id: "cost_per_thruview",
      label: "Cost / ThruView",
      hint: "TrueView for action",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "cost_per_thruview",
      invertDelta: true,
    },

    // ─── Advanced → Display → Active View (expansion) ─────────────────
    {
      id: "active_view_measurable_cost",
      label: "Active view measurable cost",
      format: "currency",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_measurable_cost_micros",
    },
    {
      id: "active_view_measurable_impressions",
      label: "Active view measurable impr.",
      format: "number",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_measurable_impressions",
    },
    {
      id: "active_view_viewable_ctr",
      label: "Viewable CTR",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_viewable_ctr",
      agg: "weighted_avg",
      aggWeight: "active_view_impressions",
    },
    {
      id: "audible_and_visible_on_completion_rate",
      label: "Audible & visible on completion",
      hint: "video display",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_audible_and_visible_on_completion_rate",
    },

    // ─── Advanced → Shopping (NEW category) ───────────────────────────
    {
      id: "shopping_item_id",
      label: "Item ID",
      hint: "merchant offer ID",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_item_id",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_item_title",
      label: "Item title",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_title",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_brand",
      label: "Brand",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_brand",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_category",
      label: "Category",
      hint: "Google product taxonomy",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_category_level1",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_custom_label_0",
      label: "Custom label 0",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_custom_attribute0",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_custom_label_1",
      label: "Custom label 1",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_custom_attribute1",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_custom_label_2",
      label: "Custom label 2",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_custom_attribute2",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_custom_label_3",
      label: "Custom label 3",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_custom_attribute3",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_custom_label_4",
      label: "Custom label 4",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_custom_attribute4",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_price",
      label: "Price",
      format: "currency",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_price",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_sale_price",
      label: "Sale price",
      format: "currency",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_sale_price",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_channel",
      label: "Channel",
      hint: "online / local",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_channel",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_channel_exclusivity",
      label: "Channel exclusivity",
      hint: "single / multi-channel",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_channel_exclusivity",
      validLevels: ["adset", "ad"],
    },
    {
      id: "shopping_product_condition",
      label: "Condition",
      hint: "new / used / refurbished",
      format: "text",
      tab: "advanced",
      category: "Shopping",
      group: "Product attributes",
      path: "segments.product_condition",
      validLevels: ["adset", "ad"],
    },

    // ─── Advanced → PMax (NEW category) ───────────────────────────────
    {
      id: "pmax_asset_group_performance_grade",
      label: "Asset group performance",
      hint: "Excellent / Good / Low",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "asset_group.ad_strength",
      validLevels: ["adset"],
    },
    {
      id: "pmax_asset_group_strength",
      label: "Asset group strength",
      hint: "headlines/images count",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "asset_group.primary_status",
      validLevels: ["adset"],
    },
    {
      id: "pmax_search_themes_contribution",
      label: "Search themes contribution",
      hint: "HIGH / MEDIUM / LOW",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "campaign_search_term_insight.category_label",
      validLevels: ["campaign"],
    },
    {
      id: "pmax_audience_signals",
      label: "Audience signals",
      hint: "first-party / interests",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "asset_group_signal.audience",
      validLevels: ["adset"],
    },
    {
      id: "pmax_asset_coverage",
      label: "Asset coverage",
      hint: "missing asset types",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "asset_group.primary_status_reasons",
      validLevels: ["adset"],
    },
    {
      id: "pmax_asset_rejected_reasons",
      label: "Rejected reasons",
      format: "text",
      tab: "advanced",
      category: "PMax",
      group: "Asset groups",
      path: "asset_group_asset.policy_summary.review_status",
      validLevels: ["adset", "ad"],
    },
    {
      id: "pmax_optimization_score",
      label: "Optimization score",
      hint: "0-100% account health",
      format: "percent",
      tab: "advanced",
      category: "PMax",
      group: "Optimization",
      path: "customer.optimization_score",
      validLevels: ["campaign"],
    },

    // ─── Advanced → Auction Insights (NOTE — separate report path) ────
    {
      id: "auction_insights_note",
      label: "Auction Insights",
      hint: "separate GAQL report",
      description:
        "Auction Insights is not a standard metric in v22 — it's a separate resource (auction_insight_domain) that requires its own GAQL query. Use the Auction Insights report path instead of selecting this here.",
      format: "text",
      tab: "advanced",
      category: "Auction Insights",
      group: "Notes",
      path: "auction_insight_domain",
      validLevels: ["campaign", "adset"],
    },
  ],
};
