/**
 * Meta Ads field catalog — mirrors the "Customize Columns" picker in
 * Meta Ads Manager (Key metrics / Tracking / Ad settings / Advanced /
 * Custom tabs with their nested categories and groups).
 *
 * ~110 direct fields are exposed here. The ~150 action sub-types (e.g.
 * `actions[action_type=offsite_conversion.fb_pixel_purchase]`) are NOT
 * pre-listed — they're added by the marketer via the Custom tab's
 * "Add conversion event" picker because they vary per pixel/account.
 *
 * `path` values reference keys we sync into `ad_data.data` JSONB. Some
 * are not yet synced — those fields display "—" until lib/zernio/sync.ts
 * adds them. Sync gap-closure is a separate follow-up commit.
 */

import type { PlatformCatalog } from "./catalog-types";

export const metaCatalog: PlatformCatalog = {
  platform: "meta",
  label: "Facebook Ads",
  brandColor: "#1877F2",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    { tab: "key_metrics", name: "Results and spend", groups: ["Results", "Spend"] },
    { tab: "key_metrics", name: "Distribution", groups: ["Reach & Impressions", "Time-based reach", "Clicks"] },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    { tab: "tracking", name: "Conversions", groups: ["Standard events", "E-commerce events", "Lead-gen events", "Engagement events", "Custom events"] },
    { tab: "tracking", name: "Attribution", groups: ["Attribution settings", "Attribution windows"] },
    { tab: "ad_settings", name: "Identity", groups: ["Names & IDs", "Account & dates", "Status"] },
    { tab: "ad_settings", name: "Schedule & budget", groups: ["Schedule", "Budget", "Bidding"] },
    { tab: "advanced", name: "Video", groups: ["Plays", "Quartiles", "Engagement", "Video rates"] },
    { tab: "advanced", name: "Engagement", groups: ["Reactions", "Page", "Other engagement"] },
    { tab: "advanced", name: "Quality", groups: ["Auction rankings", "Estimated recall"] },
  ],
  fields: [
    // ─── Key metrics → Results and spend → Results ─────────────────────
    {
      id: "results",
      label: "Results",
      description: "Total optimization-objective results.",
      format: "number",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "cost_per_result",
      label: "Cost per result",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "result_rate",
      label: "Result rate",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversionRate",
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "results_value",
      label: "Results value",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "revenue",
      isFeatured: true,
    },
    {
      id: "results_roas",
      label: "Results ROAS",
      hint: "× return",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Spend ───────────────────────────────────────────
    {
      id: "spend",
      label: "Amount spent",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "spend_pct",
      label: "Amount spent percentage",
      hint: "% of budget",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend_pct",
    },

    // ─── Key metrics → Distribution → Reach & Impressions ──────────────
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "reach",
      label: "Reach",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "reach",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "frequency",
      label: "Frequency",
      hint: "impressions per person",
      format: "ratio",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "frequency",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "reach",
    },

    // ─── Key metrics → Distribution → Clicks ───────────────────────────
    {
      id: "clicks",
      label: "Clicks (all)",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "link_clicks",
      label: "Link clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "link_clicks",
    },
    {
      id: "outbound_clicks",
      label: "Outbound clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "outbound_clicks",
    },
    {
      id: "ctr",
      label: "CTR (all)",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "link_ctr",
      label: "CTR (link)",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "link_ctr",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "unique_clicks",
      label: "Unique clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "unique_clicks",
    },
    {
      id: "unique_ctr",
      label: "Unique CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "unique_ctr",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "cpc",
      label: "CPC (all)",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "cpc_link",
      label: "Cost per link click",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc_link",
      invertDelta: true,
    },
    {
      id: "cpm",
      label: "CPM",
      hint: "per 1k impressions",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "cpp",
      label: "CPP",
      hint: "per 1k reach",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpp",
      invertDelta: true,
    },

    // ─── Tracking → Conversions → Standard events ──────────────────────
    {
      id: "purchases",
      label: "Purchases",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchases",
      isFeatured: true,
    },
    {
      id: "purchase_value",
      label: "Purchase value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchase_value",
      isFeatured: true,
    },
    {
      id: "cost_per_purchase",
      label: "Cost per purchase",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "cost_per_purchase",
      invertDelta: true,
    },
    {
      id: "purchase_roas",
      label: "Purchase ROAS",
      format: "ratio",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchase_roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "leads",
      label: "Leads",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "leads",
    },
    {
      id: "cost_per_lead",
      label: "Cost per lead",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "cost_per_lead",
      invertDelta: true,
    },
    {
      id: "add_to_cart",
      label: "Add to cart",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "add_to_cart",
    },
    {
      id: "initiate_checkout",
      label: "Initiated checkout",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "initiate_checkout",
    },
    {
      id: "landing_page_views",
      label: "Landing page views",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "landing_page_views",
      isFeatured: true,
    },
    {
      id: "complete_registration",
      label: "Complete registration",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "complete_registration",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "attribution_setting",
      label: "Attribution setting",
      format: "text",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "attribution_setting",
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "adset_name",
      label: "Ad set",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "creative_thumbnail",
      label: "Creative",
      format: "thumbnail",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_thumbnail",
      validLevels: ["ad"],
    },
    {
      id: "creative_body",
      label: "Ad copy",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_body",
      validLevels: ["ad"],
    },
    {
      id: "status",
      label: "Delivery",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "objective",
      label: "Objective",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "objective",
    },

    // ─── Ad settings → Schedule & budget ───────────────────────────────
    {
      id: "budget",
      label: "Budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "budget",
    },
    {
      id: "bid_strategy",
      label: "Bid strategy",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "bid_strategy",
    },
    {
      id: "ends",
      label: "Ends",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "end_date",
    },

    // ─── Advanced → Video → Plays ──────────────────────────────────────
    {
      id: "video_plays",
      label: "Video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_plays",
    },
    {
      id: "video_views_3s",
      label: "3-second video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_3s",
      isFeatured: true,
    },
    {
      id: "video_views_2s_continuous",
      label: "2-second continuous views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_2s",
    },
    {
      id: "thruplays",
      label: "ThruPlays",
      hint: "≥15s or full",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "thruplays",
    },
    {
      id: "cost_per_thruplay",
      label: "Cost per ThruPlay",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "cost_per_thruplay",
      invertDelta: true,
    },

    // ─── Advanced → Video → Quartiles ──────────────────────────────────
    {
      id: "video_p25",
      label: "Video plays at 25%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p25",
    },
    {
      id: "video_p50",
      label: "Video plays at 50%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p50",
    },
    {
      id: "video_p75",
      label: "Video plays at 75%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p75",
    },
    {
      id: "video_p100",
      label: "Video plays at 100%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p100",
    },
    {
      id: "avg_video_play",
      label: "Avg video play time",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "avg_video_play",
    },

    // ─── Advanced → Engagement ─────────────────────────────────────────
    {
      id: "post_engagement",
      label: "Post engagement",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_engagement",
    },
    {
      id: "post_reactions",
      label: "Post reactions",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_reactions",
    },
    {
      id: "post_comments",
      label: "Post comments",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_comments",
    },
    {
      id: "post_shares",
      label: "Post shares",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_shares",
    },
    {
      id: "post_saves",
      label: "Post saves",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_saves",
    },
    {
      id: "page_engagement",
      label: "Page engagement",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Page",
      path: "page_engagement",
    },
    {
      id: "page_likes",
      label: "Page likes",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Page",
      path: "page_likes",
    },

    // ─── Advanced → Quality (auction rankings) ─────────────────────────
    {
      id: "quality_ranking",
      label: "Quality ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "quality_ranking",
      validLevels: ["ad"],
    },
    {
      id: "engagement_rate_ranking",
      label: "Engagement rate ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "engagement_rate_ranking",
      validLevels: ["ad"],
    },
    {
      id: "conversion_rate_ranking",
      label: "Conversion rate ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "conversion_rate_ranking",
      validLevels: ["ad"],
    },

    // ─── Key metrics → Distribution → Time-based reach ─────────────────
    {
      id: "daily_reach",
      label: "Daily reach",
      hint: "unique people / day",
      description: "Average number of people who saw an ad at least once per day in the selected window.",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "daily_reach",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "weekly_reach",
      label: "Weekly reach",
      hint: "unique people / 7d",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "weekly_reach",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "monthly_reach",
      label: "Monthly reach",
      hint: "unique people / 28d",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "monthly_reach",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "daily_impressions",
      label: "Daily impressions",
      hint: "avg / day",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "daily_impressions",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "weekly_impressions",
      label: "Weekly impressions",
      hint: "avg / 7d",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "weekly_impressions",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "monthly_impressions",
      label: "Monthly impressions",
      hint: "avg / 28d",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Time-based reach",
      path: "monthly_impressions",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },

    // ─── Key metrics → Cost (additional) ───────────────────────────────
    {
      id: "cost_per_estimated_ad_recall",
      label: "Cost per estimated ad recall lift (people)",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_estimated_ad_recall",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_1000_reached",
      label: "Cost per 1,000 accounts reached",
      hint: "per 1k reach",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_1000_reached",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "reach",
    },
    {
      id: "cost_per_inline_link_click",
      label: "Cost per inline link click",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_inline_link_click",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_inline_post_engagement",
      label: "Cost per inline post engagement",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_inline_post_engagement",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_unique_click",
      label: "Cost per unique click (all)",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_unique_click",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "unique_clicks",
    },
    {
      id: "cost_per_outbound_click",
      label: "Cost per outbound click",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cost_per_outbound_click",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "outbound_clicks",
    },

    // ─── Tracking → Conversions → E-commerce events ────────────────────
    {
      id: "search",
      label: "Searches",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "search",
    },
    {
      id: "search_value",
      label: "Search value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "search_value",
    },
    {
      id: "cost_per_search",
      label: "Cost per search",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_search",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "view_content",
      label: "Content views",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "view_content",
    },
    {
      id: "view_content_value",
      label: "Content view value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "view_content_value",
    },
    {
      id: "cost_per_view_content",
      label: "Cost per content view",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_view_content",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "add_to_cart_value",
      label: "Add to cart value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "add_to_cart_value",
    },
    {
      id: "cost_per_add_to_cart",
      label: "Cost per add to cart",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_add_to_cart",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "add_payment_info",
      label: "Add payment info",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "add_payment_info",
    },
    {
      id: "add_payment_info_value",
      label: "Add payment info value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "add_payment_info_value",
    },
    {
      id: "cost_per_add_payment_info",
      label: "Cost per add payment info",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_add_payment_info",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "initiate_checkout_value",
      label: "Initiated checkout value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "initiate_checkout_value",
    },
    {
      id: "cost_per_initiate_checkout",
      label: "Cost per initiated checkout",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_initiate_checkout",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "customize_product",
      label: "Customize product",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "customize_product",
    },
    {
      id: "customize_product_value",
      label: "Customize product value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "customize_product_value",
    },
    {
      id: "cost_per_customize_product",
      label: "Cost per customize product",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_customize_product",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "subscribe",
      label: "Subscriptions",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "subscribe",
    },
    {
      id: "subscribe_value",
      label: "Subscription value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "subscribe_value",
    },
    {
      id: "cost_per_subscribe",
      label: "Cost per subscription",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_subscribe",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "start_trial",
      label: "Trials started",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "start_trial",
    },
    {
      id: "start_trial_value",
      label: "Trial value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "start_trial_value",
    },
    {
      id: "cost_per_start_trial",
      label: "Cost per trial started",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "E-commerce events",
      path: "cost_per_start_trial",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → Lead-gen events ──────────────────────
    {
      id: "submit_application",
      label: "Applications submitted",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "submit_application",
    },
    {
      id: "submit_application_value",
      label: "Application value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "submit_application_value",
    },
    {
      id: "cost_per_submit_application",
      label: "Cost per application submitted",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "cost_per_submit_application",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "schedule",
      label: "Appointments scheduled",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "schedule",
    },
    {
      id: "schedule_value",
      label: "Schedule value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "schedule_value",
    },
    {
      id: "cost_per_schedule",
      label: "Cost per appointment scheduled",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "cost_per_schedule",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "contact",
      label: "Contacts",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "contact",
    },
    {
      id: "contact_value",
      label: "Contact value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "contact_value",
    },
    {
      id: "cost_per_contact",
      label: "Cost per contact",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "cost_per_contact",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "find_location",
      label: "Find location",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "find_location",
    },
    {
      id: "cost_per_find_location",
      label: "Cost per find location",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "cost_per_find_location",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "lead_value",
      label: "Lead value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "lead_value",
    },
    {
      id: "complete_registration_value",
      label: "Registration value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "complete_registration_value",
    },
    {
      id: "cost_per_complete_registration",
      label: "Cost per registration",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Lead-gen events",
      path: "cost_per_complete_registration",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → Engagement events ────────────────────
    {
      id: "donate",
      label: "Donations",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "donate",
    },
    {
      id: "donate_value",
      label: "Donation value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "donate_value",
    },
    {
      id: "cost_per_donate",
      label: "Cost per donation",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "cost_per_donate",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "other_website_conversion",
      label: "Other website conversions",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "other_website_conversion",
    },
    {
      id: "other_website_conversion_value",
      label: "Other website conversion value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "other_website_conversion_value",
    },
    {
      id: "cost_per_other_website_conversion",
      label: "Cost per other website conversion",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "cost_per_other_website_conversion",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_landing_page_view",
      label: "Cost per landing page view",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Engagement events",
      path: "cost_per_landing_page_view",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Attribution → Attribution windows ──────────────────
    {
      id: "conversions_1d_view",
      label: "Conversions (1-day view)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "conversions_1d_view",
    },
    {
      id: "conversions_1d_click",
      label: "Conversions (1-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "conversions_1d_click",
    },
    {
      id: "conversions_7d_click",
      label: "Conversions (7-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "conversions_7d_click",
    },
    {
      id: "conversions_28d_click",
      label: "Conversions (28-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "conversions_28d_click",
    },
    {
      id: "conversions_1d_view_7d_click",
      label: "Conversions (1-day view & 7-day click)",
      description: "Default Meta attribution window for most objectives.",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "conversions_1d_view_7d_click",
    },
    {
      id: "purchase_value_1d_click",
      label: "Purchase value (1-day click)",
      format: "currency",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "purchase_value_1d_click",
    },
    {
      id: "purchase_value_7d_click",
      label: "Purchase value (7-day click)",
      format: "currency",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution windows",
      path: "purchase_value_7d_click",
    },

    // ─── Ad settings → Identity → Account & dates ──────────────────────
    {
      id: "account_name",
      label: "Account name",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "account_name",
    },
    {
      id: "account_id",
      label: "Account ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "account_id",
    },
    {
      id: "campaign_id",
      label: "Campaign ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "campaign_id",
      validLevels: ["campaign", "adset", "ad"],
    },
    {
      id: "adset_id",
      label: "Ad set ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "adset_id",
      validLevels: ["adset", "ad"],
    },
    {
      id: "ad_id",
      label: "Ad ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "ad_id",
      validLevels: ["ad"],
    },
    {
      id: "date",
      label: "Date",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "date_start",
    },
    {
      id: "day_of_week",
      label: "Day of week",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "day_of_week",
    },
    {
      id: "hour_of_day",
      label: "Hour of day",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "hour_of_day",
    },
    {
      id: "time_of_day",
      label: "Time of day (advertiser tz)",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "time_of_day",
    },
    {
      id: "time_of_day_viewer",
      label: "Time of day (viewer tz)",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Account & dates",
      path: "time_of_day_viewer",
    },

    // ─── Ad settings → Schedule & budget (additional) ──────────────────
    {
      id: "daily_budget",
      label: "Daily budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "daily_budget",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "lifetime_budget",
      label: "Lifetime budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "lifetime_budget",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "spend_cap",
      label: "Spend cap",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "spend_cap",
      validLevels: ["campaign"],
    },
    {
      id: "account_spend_cap",
      label: "Account spend cap",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "account_spend_cap",
    },
    {
      id: "account_spend_limit",
      label: "Account spend limit",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "account_spend_limit",
    },
    {
      id: "starts",
      label: "Starts",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "start_date",
    },
    {
      id: "schedule_type",
      label: "Schedule type",
      hint: "ASAP / scheduled",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "schedule_type",
    },
    {
      id: "bid_amount",
      label: "Bid amount",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bidding",
      path: "bid_amount",
      validLevels: ["adset"],
    },
    {
      id: "optimization_goal",
      label: "Optimization goal",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bidding",
      path: "optimization_goal",
      validLevels: ["adset"],
    },
    {
      id: "billing_event",
      label: "Billing event",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bidding",
      path: "billing_event",
      validLevels: ["adset"],
    },
    {
      id: "buying_type",
      label: "Buying type",
      hint: "auction / reserved",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bidding",
      path: "buying_type",
      validLevels: ["campaign"],
    },

    // ─── Advanced → Video → Plays (additional) ─────────────────────────
    {
      id: "video_views_10s",
      label: "10-second video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_10s",
    },
    {
      id: "video_views_15s",
      label: "15-second video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_15s",
    },
    {
      id: "video_views_30s",
      label: "30-second video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_30s",
    },
    {
      id: "cost_per_video_view_10s",
      label: "Cost per 10-second video play",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "cost_per_video_view_10s",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_video_view_3s",
      label: "Cost per 3-second video play",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "cost_per_video_view_3s",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "video_p50_sound_on",
      label: "Video plays at 50% with sound on",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p50_sound_on",
    },
    {
      id: "video_p100_sound_on",
      label: "Video plays at 100% with sound on",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p100_sound_on",
    },

    // ─── Advanced → Video → Engagement (additional) ────────────────────
    {
      id: "video_avg_watch_time",
      label: "Video average watch time",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Engagement",
      path: "video_avg_watch_time",
      agg: "weighted_avg",
      aggWeight: "video_views_3s",
    },
    {
      id: "video_total_watch_time",
      label: "Video total watch time",
      hint: "seconds",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Engagement",
      path: "video_total_watch_time",
    },
    {
      id: "video_reactions",
      label: "Video reactions",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Engagement",
      path: "video_reactions",
    },
    {
      id: "video_shares",
      label: "Video shares",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Engagement",
      path: "video_shares",
    },
    {
      id: "video_comments",
      label: "Video comments",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Engagement",
      path: "video_comments",
    },

    // ─── Advanced → Video → Video rates ────────────────────────────────
    {
      id: "thruplay_through_rate",
      label: "ThruPlay through-rate",
      hint: "ThruPlays / impressions",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "thruplay_through_rate",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "thruplay_rate",
      label: "ThruPlay rate",
      hint: "ThruPlays / 3s plays",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "thruplay_rate",
      agg: "weighted_avg",
      aggWeight: "video_views_3s",
    },
    {
      id: "video_sound_on_rate",
      label: "Video sound-on rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "video_sound_on_rate",
      agg: "weighted_avg",
      aggWeight: "video_views_3s",
    },
    {
      id: "video_p25_rate",
      label: "Video play 25% rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "video_p25_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "video_p50_rate",
      label: "Video play 50% rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "video_p50_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "video_p75_rate",
      label: "Video play 75% rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "video_p75_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "video_p100_rate",
      label: "Video play 100% rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Video rates",
      path: "video_p100_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },

    // ─── Advanced → Engagement → Other engagement ──────────────────────
    {
      id: "page_mentions",
      label: "Page mentions",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "page_mentions",
    },
    {
      id: "page_tab_views",
      label: "Page tab views",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "page_tab_views",
    },
    {
      id: "page_cta_clicks",
      label: "Page CTA clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "page_cta_clicks",
    },
    {
      id: "photo_views",
      label: "Photo views",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "photo_views",
    },
    {
      id: "checkins",
      label: "Check-ins",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "checkins",
    },
    {
      id: "event_responses",
      label: "Event responses",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "event_responses",
    },
    {
      id: "negative_feedback",
      label: "Negative feedback",
      description: "Hides, reports, and 'don't show this' actions on the ad.",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "negative_feedback",
      invertDelta: true,
    },
    {
      id: "messaging_conversation_started",
      label: "Messaging conversations started",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "messaging_conversation_started",
    },
    {
      id: "cost_per_messaging_conversation_started",
      label: "Cost per messaging conversation started",
      format: "currency",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "cost_per_messaging_conversation_started",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "inline_post_engagement",
      label: "Inline post engagement",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "inline_post_engagement",
    },
    {
      id: "inline_link_clicks",
      label: "Inline link clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Other engagement",
      path: "inline_link_clicks",
    },

    // ─── Advanced → Quality → Estimated recall ─────────────────────────
    {
      id: "estimated_ad_recall_lift_people",
      label: "Estimated ad recall lift (people)",
      description: "Estimated number of people likely to remember seeing your ad if asked within 2 days.",
      format: "number",
      tab: "advanced",
      category: "Quality",
      group: "Estimated recall",
      path: "estimated_ad_recall_lift_people",
    },
    {
      id: "estimated_ad_recall_lift_rate",
      label: "Estimated ad recall lift rate",
      hint: "% lift over baseline",
      format: "percent",
      tab: "advanced",
      category: "Quality",
      group: "Estimated recall",
      path: "estimated_ad_recall_lift_rate",
      agg: "weighted_avg",
      aggWeight: "reach",
    },
  ],
};
