/**
 * Google Ads field catalog.
 *
 * Google's metric model differs from Meta/TikTok — Resources × Metrics ×
 * Segments via GAQL. We expose the user-friendly subset; SIS family is
 * Campaign+AdGroup-only (not at Ad level), and Quality Score is keyword-
 * level only and surfaced in Advanced.
 *
 * ~130 metrics in v22 API; ~50 curated here as featured.
 */

import type { PlatformCatalog } from "./catalog-types";

export const googleCatalog: PlatformCatalog = {
  platform: "google",
  label: "Google Ads",
  brandColor: "#4285F4",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    {
      tab: "key_metrics",
      name: "Performance",
      groups: ["Conversions", "Clicks & Impressions", "Engagement", "Phone calls"],
    },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    {
      tab: "tracking",
      name: "Conversions",
      groups: ["All conversions", "Attribution", "Per-action"],
    },
    {
      tab: "ad_settings",
      name: "Identity",
      groups: ["Names & IDs", "Status", "Schedule & status"],
    },
    { tab: "advanced", name: "Search Impression Share", groups: ["Share", "Position", "Lost"] },
    { tab: "advanced", name: "Quality", groups: ["Quality score (keyword)", "Bid estimates"] },
    { tab: "advanced", name: "Video", groups: ["TrueView"] },
    { tab: "advanced", name: "Display", groups: ["Active View"] },
    { tab: "advanced", name: "Shopping", groups: ["Product attributes"] },
    { tab: "advanced", name: "PMax", groups: ["Asset groups", "Optimization"] },
    { tab: "advanced", name: "Auction Insights", groups: ["Notes"] },
  ],
  fields: [
    // ─── Key metrics → Performance → Conversions ──────────────────────
    {
      id: "conversions",
      label: "Conversions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "conversion_value",
      label: "Conv. value",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "revenue",
      isFeatured: true,
    },
    {
      id: "cost_per_conversion",
      label: "Cost / conv.",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "value_per_conversion",
      label: "Value / conv.",
      format: "currency",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "value_per_conversion",
      agg: "weighted_avg",
      aggWeight: "conversions",
    },
    {
      id: "conversion_rate",
      label: "Conv. rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "conversionRate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "roas",
      label: "ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Performance",
      group: "Conversions",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Performance → Clicks & Impressions ─────────────
    {
      id: "clicks",
      label: "Clicks",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ctr",
      label: "CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "interactions",
      label: "Interactions",
      format: "number",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "interactions",
    },
    {
      id: "interaction_rate",
      label: "Interaction rate",
      format: "percent",
      tab: "key_metrics",
      category: "Performance",
      group: "Clicks & Impressions",
      path: "interaction_rate",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "spend",
      label: "Cost",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "avg_cpc",
      label: "Avg. CPC",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "avg_cpm",
      label: "Avg. CPM",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "avg_cpv",
      label: "Avg. CPV",
      hint: "TrueView",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "avg_cpv",
      invertDelta: true,
    },

    // ─── Tracking → Conversions → All conversions ──────────────────────
    {
      id: "all_conversions",
      label: "All conversions",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions",
    },
    {
      id: "all_conversions_value",
      label: "All conv. value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "all_conversions_value",
    },
    {
      id: "view_through_conversions",
      label: "View-through conv.",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "view_through_conversions",
      isFeatured: true,
    },
    {
      id: "cross_device_conversions",
      label: "Cross-device conv.",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "All conversions",
      path: "cross_device_conversions",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "current_model_attributed_conversions",
      label: "Conv. (current model)",
      hint: "data-driven attribution",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Attribution",
      path: "current_model_attributed_conversions",
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ad_group_name",
      label: "Ad group",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "campaign_channel_type",
      label: "Channel",
      hint: "Search/Display/PMax/etc",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_channel_type",
      isFeatured: true,
    },
    {
      id: "network",
      label: "Network",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "network",
    },
    {
      id: "status",
      label: "Status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },

    // ─── Advanced → Search Impression Share → Share ────────────────────
    {
      id: "search_impression_share",
      label: "Search impr. share",
      hint: "% of available auctions won",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Share",
      path: "search_impression_share",
      validLevels: ["campaign", "adset"],
      isFeatured: true,
    },
    {
      id: "search_click_share",
      label: "Click share",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Share",
      path: "search_click_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Position ─────────────────────────────────────
    {
      id: "search_top_impression_share",
      label: "Top impr. share",
      hint: "above search results",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_top_impression_share",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "search_absolute_top_impression_share",
      label: "Abs. top impr. share",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Position",
      path: "search_absolute_top_impression_share",
      validLevels: ["campaign", "adset"],
    },

    // ─── Advanced → SIS → Lost (the differentiator metric) ─────────────
    {
      id: "search_budget_lost_impression_share",
      label: "Search lost IS (budget)",
      hint: "% lost to budget cap",
      description:
        "High budget-lost = give the campaign more money, it can scale. Pair with Lost (Rank).",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_budget_lost_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
      isFeatured: true,
    },
    {
      id: "search_rank_lost_impression_share",
      label: "Search lost IS (rank)",
      hint: "% lost to ad rank",
      description:
        "High rank-lost = improve QS / bids / creative. DO NOT just give more money.",
      format: "percent",
      tab: "advanced",
      category: "Search Impression Share",
      group: "Lost",
      path: "search_rank_lost_impression_share",
      validLevels: ["campaign", "adset"],
      invertDelta: true,
      isFeatured: true,
    },

    // ─── Advanced → Quality (keyword-level) ────────────────────────────
    {
      id: "historical_quality_score",
      label: "Quality score",
      hint: "1-10, keyword-level",
      format: "number",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_creative_quality_score",
      label: "Ad relevance",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_creative_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_landing_page_quality_score",
      label: "Landing page exp.",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_landing_page_quality_score",
      validLevels: ["adset", "ad"],
    },
    {
      id: "historical_search_predicted_ctr",
      label: "Expected CTR",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Quality score (keyword)",
      path: "historical_search_predicted_ctr",
      validLevels: ["adset", "ad"],
    },

    // ─── Advanced → Video → TrueView ───────────────────────────────────
    {
      id: "video_views",
      label: "Video views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_views",
    },
    {
      id: "video_view_rate",
      label: "View rate",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_view_rate",
    },
    {
      id: "video_quartile_p25_rate",
      label: "25% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p25_rate",
    },
    {
      id: "video_quartile_p50_rate",
      label: "50% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p50_rate",
    },
    {
      id: "video_quartile_p75_rate",
      label: "75% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p75_rate",
    },
    {
      id: "video_quartile_p100_rate",
      label: "100% played",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "TrueView",
      path: "video_quartile_p100_rate",
    },

    // ─── Advanced → Display → Active View ──────────────────────────────
    {
      id: "active_view_impressions",
      label: "Viewable impr.",
      format: "number",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_impressions",
    },
    {
      id: "active_view_viewability",
      label: "Viewability",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_viewability",
    },
    {
      id: "active_view_ctr",
      label: "Active view CTR",
      format: "percent",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_ctr",
    },
    {
      id: "active_view_cpm",
      label: "Active view CPM",
      format: "currency",
      tab: "advanced",
      category: "Display",
      group: "Active View",
      path: "active_view_cpm",
      invertDelta: true,
    },
  ],
};
