/**
 * TikTok Ads field catalog — same column-picker UX as Meta but with
 * TikTok's metric vocabulary. Ad-Group instead of Ad-Set; video metrics
 * are stronger here because TikTok is video-first.
 *
 * Based on TikTok Marketing API v1.3 /report/integrated/get/.
 * ~150 metrics in the API; we curate the ~55 most-used with isFeatured.
 */

import type { PlatformCatalog } from "./catalog-types";

export const tiktokCatalog: PlatformCatalog = {
  platform: "tiktok",
  label: "TikTok Ads",
  brandColor: "#25F4EE",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    { tab: "key_metrics", name: "Results and spend", groups: ["Results", "Spend"] },
    { tab: "key_metrics", name: "Distribution", groups: ["Reach & Impressions", "Clicks"] },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    { tab: "tracking", name: "Conversions", groups: ["Web", "App", "TikTok shop", "Offline"] },
    { tab: "tracking", name: "Attribution", groups: ["Attribution settings"] },
    { tab: "ad_settings", name: "Identity", groups: ["Names & IDs", "Status"] },
    { tab: "advanced", name: "Video", groups: ["Plays", "Quartiles", "Hook & hold"] },
    { tab: "advanced", name: "Engagement", groups: ["Interactions", "Profile"] },
  ],
  fields: [
    // ─── Key metrics → Results and spend → Results ─────────────────────
    {
      id: "results",
      label: "Results",
      format: "number",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "cost_per_result",
      label: "Cost per result",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "result_rate",
      label: "Result rate",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversionRate",
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "complete_payment_roas",
      label: "Complete payment ROAS",
      hint: "TikTok official ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "complete_payment_roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "roas",
      label: "ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Spend ───────────────────────────────────────────
    {
      id: "spend",
      label: "Cost",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },

    // ─── Key metrics → Distribution → Reach & Impressions ──────────────
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "reach",
      label: "Reach",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "reach",
      isFeatured: true,
    },
    {
      id: "frequency",
      label: "Frequency",
      format: "ratio",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "frequency",
      agg: "weighted_avg",
      aggWeight: "reach",
    },

    // ─── Key metrics → Distribution → Clicks ───────────────────────────
    {
      id: "clicks",
      label: "Clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ctr",
      label: "CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "cpc",
      label: "CPC",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "cpm",
      label: "CPM",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },

    // ─── Tracking → Conversions ────────────────────────────────────────
    {
      id: "purchases_web",
      label: "Purchases (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "purchases_web",
      isFeatured: true,
    },
    {
      id: "purchase_value_web",
      label: "Purchase value (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "purchase_value_web",
    },
    {
      id: "add_to_cart_web",
      label: "Add to cart (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "add_to_cart_web",
    },
    {
      id: "checkout_initiated_web",
      label: "Initiate checkout (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "checkout_initiated_web",
    },
    {
      id: "purchases_app",
      label: "Purchases (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "purchases_app",
    },
    {
      id: "purchase_value_app",
      label: "Purchase value (app)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "purchase_value_app",
    },
    {
      id: "app_installs",
      label: "App installs",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "app_installs",
    },
    {
      id: "purchases_shop",
      label: "Purchases (TikTok shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "purchases_shop",
    },
    {
      id: "gross_revenue_shop",
      label: "Gross revenue (shop)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "gross_revenue_shop",
    },
    {
      id: "purchases_offline",
      label: "Purchases (offline)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "purchases_offline",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "attribution_setting",
      label: "Attribution setting",
      hint: "click + engaged-view",
      format: "text",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "attribution_setting",
    },
    {
      id: "engaged_view_conversions",
      label: "Engaged-view conversions",
      hint: "≥6s no click",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "engaged_view_conversions",
      isFeatured: true,
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "adgroup_name",
      label: "Ad group",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "creative_thumbnail",
      label: "Creative",
      format: "thumbnail",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_thumbnail",
      validLevels: ["ad"],
    },
    {
      id: "creative_body",
      label: "Ad text",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_body",
      validLevels: ["ad"],
    },
    {
      id: "is_spark_ad",
      label: "Spark ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "is_spark_ad",
      validLevels: ["ad"],
    },
    {
      id: "status",
      label: "Status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "objective",
      label: "Objective",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "objective",
    },

    // ─── Advanced → Video → Plays ──────────────────────────────────────
    {
      id: "video_play_actions",
      label: "Video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_plays",
    },
    {
      id: "video_views_2s",
      label: "2-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_2s",
      isFeatured: true,
    },
    {
      id: "video_views_6s",
      label: "6-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_6s",
      isFeatured: true,
    },
    {
      id: "video_views_15s",
      label: "15-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_15s",
    },
    {
      id: "avg_video_play",
      label: "Avg video play time",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "avg_video_play",
    },

    // ─── Advanced → Video → Quartiles ──────────────────────────────────
    {
      id: "video_p25",
      label: "Quartile 25%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p25",
    },
    {
      id: "video_p50",
      label: "Quartile 50%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p50",
    },
    {
      id: "video_p75",
      label: "Quartile 75%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p75",
    },
    {
      id: "video_p100",
      label: "Full views (100%)",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p100",
      isFeatured: true,
    },

    // ─── Advanced → Video → Hook & hold (TikTok-specific killer cards) ─
    {
      id: "hook_rate",
      label: "Hook rate",
      hint: "2s ÷ impressions",
      description: "TikTok's leading creative-quality indicator. >40% is elite, <25% kill.",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hook_rate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "hold_rate",
      label: "Hold rate",
      hint: "6s ÷ 2s",
      description: "Did the hook deliver on its promise? Decouples hook from hold.",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hold_rate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "video_views_2s",
    },
    {
      id: "completion_rate",
      label: "Completion rate",
      hint: "100% ÷ plays",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "completion_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },

    // ─── Advanced → Engagement ─────────────────────────────────────────
    {
      id: "likes",
      label: "Likes",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "likes",
    },
    {
      id: "comments",
      label: "Comments",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "comments",
    },
    {
      id: "shares",
      label: "Shares",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "shares",
    },
    {
      id: "follows",
      label: "Follows",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "follows",
    },
    {
      id: "profile_visits",
      label: "Profile visits",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "profile_visits",
    },
  ],
};
