/**
 * Meta Ads field catalog — mirrors the "Customize Columns" picker in
 * Meta Ads Manager (Key metrics / Tracking / Ad settings / Advanced /
 * Custom tabs with their nested categories and groups).
 *
 * ~110 direct fields are exposed here. The ~150 action sub-types (e.g.
 * `actions[action_type=offsite_conversion.fb_pixel_purchase]`) are NOT
 * pre-listed — they're added by the marketer via the Custom tab's
 * "Add conversion event" picker because they vary per pixel/account.
 *
 * `path` values reference keys we sync into `ad_data.data` JSONB. Some
 * are not yet synced — those fields display "—" until lib/zernio/sync.ts
 * adds them. Sync gap-closure is a separate follow-up commit.
 */

import type { PlatformCatalog } from "./catalog-types";

export const metaCatalog: PlatformCatalog = {
  platform: "meta",
  label: "Facebook Ads",
  brandColor: "#1877F2",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    { tab: "key_metrics", name: "Results and spend", groups: ["Results", "Spend"] },
    { tab: "key_metrics", name: "Distribution", groups: ["Reach & Impressions", "Clicks"] },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    { tab: "tracking", name: "Conversions", groups: ["Standard events", "Custom events"] },
    { tab: "tracking", name: "Attribution", groups: ["Attribution settings"] },
    { tab: "ad_settings", name: "Identity", groups: ["Names & IDs", "Status"] },
    { tab: "ad_settings", name: "Schedule & budget", groups: ["Schedule", "Budget"] },
    { tab: "advanced", name: "Video", groups: ["Plays", "Quartiles", "Engagement"] },
    { tab: "advanced", name: "Engagement", groups: ["Reactions", "Page"] },
    { tab: "advanced", name: "Quality", groups: ["Auction rankings"] },
  ],
  fields: [
    // ─── Key metrics → Results and spend → Results ─────────────────────
    {
      id: "results",
      label: "Results",
      description: "Total optimization-objective results.",
      format: "number",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "cost_per_result",
      label: "Cost per result",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "result_rate",
      label: "Result rate",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversionRate",
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "results_value",
      label: "Results value",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "revenue",
      isFeatured: true,
    },
    {
      id: "results_roas",
      label: "Results ROAS",
      hint: "× return",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Spend ───────────────────────────────────────────
    {
      id: "spend",
      label: "Amount spent",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "spend_pct",
      label: "Amount spent percentage",
      hint: "% of budget",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend_pct",
    },

    // ─── Key metrics → Distribution → Reach & Impressions ──────────────
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "reach",
      label: "Reach",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "reach",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "frequency",
      label: "Frequency",
      hint: "impressions per person",
      format: "ratio",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "frequency",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "reach",
    },

    // ─── Key metrics → Distribution → Clicks ───────────────────────────
    {
      id: "clicks",
      label: "Clicks (all)",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "link_clicks",
      label: "Link clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "link_clicks",
    },
    {
      id: "outbound_clicks",
      label: "Outbound clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "outbound_clicks",
    },
    {
      id: "ctr",
      label: "CTR (all)",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "link_ctr",
      label: "CTR (link)",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "link_ctr",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "unique_clicks",
      label: "Unique clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "unique_clicks",
    },
    {
      id: "unique_ctr",
      label: "Unique CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "unique_ctr",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "cpc",
      label: "CPC (all)",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "cpc_link",
      label: "Cost per link click",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc_link",
      invertDelta: true,
    },
    {
      id: "cpm",
      label: "CPM",
      hint: "per 1k impressions",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "cpp",
      label: "CPP",
      hint: "per 1k reach",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpp",
      invertDelta: true,
    },

    // ─── Tracking → Conversions → Standard events ──────────────────────
    {
      id: "purchases",
      label: "Purchases",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchases",
      isFeatured: true,
    },
    {
      id: "purchase_value",
      label: "Purchase value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchase_value",
      isFeatured: true,
    },
    {
      id: "cost_per_purchase",
      label: "Cost per purchase",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "cost_per_purchase",
      invertDelta: true,
    },
    {
      id: "purchase_roas",
      label: "Purchase ROAS",
      format: "ratio",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "purchase_roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "leads",
      label: "Leads",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "leads",
    },
    {
      id: "cost_per_lead",
      label: "Cost per lead",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "cost_per_lead",
      invertDelta: true,
    },
    {
      id: "add_to_cart",
      label: "Add to cart",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "add_to_cart",
    },
    {
      id: "initiate_checkout",
      label: "Initiated checkout",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "initiate_checkout",
    },
    {
      id: "landing_page_views",
      label: "Landing page views",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "landing_page_views",
      isFeatured: true,
    },
    {
      id: "complete_registration",
      label: "Complete registration",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Standard events",
      path: "complete_registration",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "attribution_setting",
      label: "Attribution setting",
      format: "text",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "attribution_setting",
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "adset_name",
      label: "Ad set",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "creative_thumbnail",
      label: "Creative",
      format: "thumbnail",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_thumbnail",
      validLevels: ["ad"],
    },
    {
      id: "creative_body",
      label: "Ad copy",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_body",
      validLevels: ["ad"],
    },
    {
      id: "status",
      label: "Delivery",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "objective",
      label: "Objective",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "objective",
    },

    // ─── Ad settings → Schedule & budget ───────────────────────────────
    {
      id: "budget",
      label: "Budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "budget",
    },
    {
      id: "bid_strategy",
      label: "Bid strategy",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "bid_strategy",
    },
    {
      id: "ends",
      label: "Ends",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "end_date",
    },

    // ─── Advanced → Video → Plays ──────────────────────────────────────
    {
      id: "video_plays",
      label: "Video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_plays",
    },
    {
      id: "video_views_3s",
      label: "3-second video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_3s",
      isFeatured: true,
    },
    {
      id: "video_views_2s_continuous",
      label: "2-second continuous views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_2s",
    },
    {
      id: "thruplays",
      label: "ThruPlays",
      hint: "≥15s or full",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "thruplays",
    },
    {
      id: "cost_per_thruplay",
      label: "Cost per ThruPlay",
      format: "currency",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "cost_per_thruplay",
      invertDelta: true,
    },

    // ─── Advanced → Video → Quartiles ──────────────────────────────────
    {
      id: "video_p25",
      label: "Video plays at 25%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p25",
    },
    {
      id: "video_p50",
      label: "Video plays at 50%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p50",
    },
    {
      id: "video_p75",
      label: "Video plays at 75%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p75",
    },
    {
      id: "video_p100",
      label: "Video plays at 100%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p100",
    },
    {
      id: "avg_video_play",
      label: "Avg video play time",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "avg_video_play",
    },

    // ─── Advanced → Engagement ─────────────────────────────────────────
    {
      id: "post_engagement",
      label: "Post engagement",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_engagement",
    },
    {
      id: "post_reactions",
      label: "Post reactions",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_reactions",
    },
    {
      id: "post_comments",
      label: "Post comments",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_comments",
    },
    {
      id: "post_shares",
      label: "Post shares",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_shares",
    },
    {
      id: "post_saves",
      label: "Post saves",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Reactions",
      path: "post_saves",
    },
    {
      id: "page_engagement",
      label: "Page engagement",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Page",
      path: "page_engagement",
    },
    {
      id: "page_likes",
      label: "Page likes",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Page",
      path: "page_likes",
    },

    // ─── Advanced → Quality (auction rankings) ─────────────────────────
    {
      id: "quality_ranking",
      label: "Quality ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "quality_ranking",
      validLevels: ["ad"],
    },
    {
      id: "engagement_rate_ranking",
      label: "Engagement rate ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "engagement_rate_ranking",
      validLevels: ["ad"],
    },
    {
      id: "conversion_rate_ranking",
      label: "Conversion rate ranking",
      format: "text",
      tab: "advanced",
      category: "Quality",
      group: "Auction rankings",
      path: "conversion_rate_ranking",
      validLevels: ["ad"],
    },
  ],
};
