/**
 * TikTok Ads field catalog — same column-picker UX as Meta but with
 * TikTok's metric vocabulary. Ad-Group instead of Ad-Set; video metrics
 * are stronger here because TikTok is video-first.
 *
 * Based on TikTok Marketing API v1.3 /report/integrated/get/.
 * ~150 metrics in the API; we curate the ~55 most-used with isFeatured.
 */

import type { PlatformCatalog } from "./catalog-types";

export const tiktokCatalog: PlatformCatalog = {
  platform: "tiktok",
  label: "TikTok Ads",
  brandColor: "#25F4EE",
  tabs: [
    { id: "key_metrics", label: "Key metrics" },
    { id: "tracking", label: "Tracking" },
    { id: "ad_settings", label: "Ad settings" },
    { id: "advanced", label: "Advanced" },
    { id: "custom", label: "Custom" },
  ],
  categories: [
    { tab: "key_metrics", name: "Results and spend", groups: ["Results", "Spend"] },
    { tab: "key_metrics", name: "Distribution", groups: ["Reach & Impressions", "Clicks"] },
    { tab: "key_metrics", name: "Cost", groups: ["Cost"] },
    { tab: "tracking", name: "Conversions", groups: ["Web", "App", "TikTok shop", "Offline"] },
    { tab: "tracking", name: "Attribution", groups: ["Attribution settings", "Click windows", "Engaged-view windows"] },
    { tab: "ad_settings", name: "Identity", groups: ["Names & IDs", "Status"] },
    { tab: "ad_settings", name: "Schedule & budget", groups: ["Budget", "Bid & optimization", "Schedule"] },
    { tab: "advanced", name: "Video", groups: ["Plays", "Quartiles", "Hook & hold", "Retention"] },
    { tab: "advanced", name: "Engagement", groups: ["Interactions", "Profile"] },
    { tab: "advanced", name: "Audience demographics", groups: ["Top segments"] },
    { tab: "advanced", name: "Spark Ads & creator", groups: ["Creator", "Post & music"] },
  ],
  fields: [
    // ─── Key metrics → Results and spend → Results ─────────────────────
    {
      id: "results",
      label: "Results",
      format: "number",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "cost_per_result",
      label: "Cost per result",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "cpa",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "result_rate",
      label: "Result rate",
      format: "percent",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "conversionRate",
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "complete_payment_roas",
      label: "Complete payment ROAS",
      hint: "TikTok official ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "complete_payment_roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "roas",
      label: "ROAS",
      format: "ratio",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Results",
      path: "roas",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Key metrics → Spend ───────────────────────────────────────────
    {
      id: "spend",
      label: "Cost",
      format: "currency",
      tab: "key_metrics",
      category: "Results and spend",
      group: "Spend",
      path: "spend",
      isDefault: true,
      isFeatured: true,
    },

    // ─── Key metrics → Distribution → Reach & Impressions ──────────────
    {
      id: "impressions",
      label: "Impressions",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "impressions",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "reach",
      label: "Reach",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "reach",
      isFeatured: true,
    },
    {
      id: "frequency",
      label: "Frequency",
      format: "ratio",
      tab: "key_metrics",
      category: "Distribution",
      group: "Reach & Impressions",
      path: "frequency",
      agg: "weighted_avg",
      aggWeight: "reach",
    },

    // ─── Key metrics → Distribution → Clicks ───────────────────────────
    {
      id: "clicks",
      label: "Clicks",
      format: "number",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "clicks",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "ctr",
      label: "CTR",
      format: "percent",
      tab: "key_metrics",
      category: "Distribution",
      group: "Clicks",
      path: "ctr",
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },

    // ─── Key metrics → Cost ────────────────────────────────────────────
    {
      id: "cpc",
      label: "CPC",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpc",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "clicks",
    },
    {
      id: "cpm",
      label: "CPM",
      format: "currency",
      tab: "key_metrics",
      category: "Cost",
      group: "Cost",
      path: "cpm",
      invertDelta: true,
      isDefault: true,
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },

    // ─── Tracking → Conversions ────────────────────────────────────────
    {
      id: "purchases_web",
      label: "Purchases (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "purchases_web",
      isFeatured: true,
    },
    {
      id: "purchase_value_web",
      label: "Purchase value (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "purchase_value_web",
    },
    {
      id: "add_to_cart_web",
      label: "Add to cart (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "add_to_cart_web",
    },
    {
      id: "checkout_initiated_web",
      label: "Initiate checkout (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "checkout_initiated_web",
    },
    {
      id: "purchases_app",
      label: "Purchases (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "purchases_app",
    },
    {
      id: "purchase_value_app",
      label: "Purchase value (app)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "purchase_value_app",
    },
    {
      id: "app_installs",
      label: "App installs",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "app_installs",
    },
    {
      id: "purchases_shop",
      label: "Purchases (TikTok shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "purchases_shop",
    },
    {
      id: "gross_revenue_shop",
      label: "Gross revenue (shop)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "gross_revenue_shop",
    },
    {
      id: "purchases_offline",
      label: "Purchases (offline)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "purchases_offline",
    },

    // ─── Tracking → Attribution ────────────────────────────────────────
    {
      id: "attribution_setting",
      label: "Attribution setting",
      hint: "click + engaged-view",
      format: "text",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "attribution_setting",
    },
    {
      id: "engaged_view_conversions",
      label: "Engaged-view conversions",
      hint: "≥6s no click",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Attribution settings",
      path: "engaged_view_conversions",
      isFeatured: true,
    },

    // ─── Ad settings → Identity ────────────────────────────────────────
    {
      id: "campaign_name",
      label: "Campaign",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_name",
      validLevels: ["campaign", "adset", "ad"],
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "adgroup_name",
      label: "Ad group",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_name",
      validLevels: ["adset", "ad"],
      isFeatured: true,
    },
    {
      id: "ad_name",
      label: "Ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_name",
      validLevels: ["ad"],
      isFeatured: true,
    },
    {
      id: "creative_thumbnail",
      label: "Creative",
      format: "thumbnail",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_thumbnail",
      validLevels: ["ad"],
    },
    {
      id: "creative_body",
      label: "Ad text",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "creative_body",
      validLevels: ["ad"],
    },
    {
      id: "is_spark_ad",
      label: "Spark ad",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "is_spark_ad",
      validLevels: ["ad"],
    },
    {
      id: "status",
      label: "Status",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "status",
      isDefault: true,
      isFeatured: true,
    },
    {
      id: "objective",
      label: "Objective",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Status",
      path: "objective",
    },

    // ─── Advanced → Video → Plays ──────────────────────────────────────
    {
      id: "video_play_actions",
      label: "Video plays",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_plays",
    },
    {
      id: "video_views_2s",
      label: "2-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_2s",
      isFeatured: true,
    },
    {
      id: "video_views_6s",
      label: "6-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_6s",
      isFeatured: true,
    },
    {
      id: "video_views_15s",
      label: "15-second views",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_15s",
    },
    {
      id: "avg_video_play",
      label: "Avg video play time",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "avg_video_play",
    },

    // ─── Advanced → Video → Quartiles ──────────────────────────────────
    {
      id: "video_p25",
      label: "Quartile 25%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p25",
    },
    {
      id: "video_p50",
      label: "Quartile 50%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p50",
    },
    {
      id: "video_p75",
      label: "Quartile 75%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p75",
    },
    {
      id: "video_p100",
      label: "Full views (100%)",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Quartiles",
      path: "video_p100",
      isFeatured: true,
    },

    // ─── Advanced → Video → Hook & hold (TikTok-specific killer cards) ─
    {
      id: "hook_rate",
      label: "Hook rate",
      hint: "2s ÷ impressions",
      description: "TikTok's leading creative-quality indicator. >40% is elite, <25% kill.",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hook_rate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "hold_rate",
      label: "Hold rate",
      hint: "6s ÷ 2s",
      description: "Did the hook deliver on its promise? Decouples hook from hold.",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hold_rate",
      isFeatured: true,
      agg: "weighted_avg",
      aggWeight: "video_views_2s",
    },
    {
      id: "completion_rate",
      label: "Completion rate",
      hint: "100% ÷ plays",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "completion_rate",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },

    // ─── Advanced → Engagement ─────────────────────────────────────────
    {
      id: "likes",
      label: "Likes",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "likes",
    },
    {
      id: "comments",
      label: "Comments",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "comments",
    },
    {
      id: "shares",
      label: "Shares",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "shares",
    },
    {
      id: "follows",
      label: "Follows",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "follows",
    },
    {
      id: "profile_visits",
      label: "Profile visits",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "profile_visits",
    },

    // ─── EXPANSION v2 — TikTok Marketing API v1.3 reports parity ───────
    // ─── Tracking → Conversions → Web (expanded) ───────────────────────
    {
      id: "registration_web",
      label: "Registration (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "registration_web",
    },
    {
      id: "cost_per_registration_web",
      label: "Cost per registration (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_registration_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "button_click_web",
      label: "Button click (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "button_click_web",
    },
    {
      id: "cost_per_button_click_web",
      label: "Cost per button click (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_button_click_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "view_content_web",
      label: "View content (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "view_content_web",
    },
    {
      id: "cost_per_view_content_web",
      label: "Cost per view content (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_view_content_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "add_payment_info_web",
      label: "Add payment info (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "add_payment_info_web",
    },
    {
      id: "cost_per_add_payment_info_web",
      label: "Cost per add payment info (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_add_payment_info_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "search_web",
      label: "Search (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "search_web",
    },
    {
      id: "contact_web",
      label: "Contact (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "contact_web",
    },
    {
      id: "complete_payment_value_web",
      label: "Complete payment value (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "complete_payment_value_web",
    },
    {
      id: "sign_up_web",
      label: "Sign up (web)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "sign_up_web",
    },
    {
      id: "cost_per_sign_up_web",
      label: "Cost per sign up (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_sign_up_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_purchase_web",
      label: "Cost per purchase (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_purchase_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_add_to_cart_web",
      label: "Cost per add to cart (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_add_to_cart_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_checkout_initiated_web",
      label: "Cost per initiate checkout (web)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Web",
      path: "cost_per_checkout_initiated_web",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → App (expanded) ───────────────────────
    {
      id: "complete_payment_app",
      label: "Complete payment (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "complete_payment_app",
    },
    {
      id: "complete_payment_value_app",
      label: "Complete payment value (app)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "complete_payment_value_app",
    },
    {
      id: "total_app_event",
      label: "Total app events",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "total_app_event",
    },
    {
      id: "app_install_value",
      label: "App install value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "app_install_value",
    },
    {
      id: "cost_per_app_install",
      label: "Cost per app install",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "cost_per_app_install",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "in_app_purchase",
      label: "In-app purchase",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "in_app_purchase",
    },
    {
      id: "cost_per_in_app_purchase",
      label: "Cost per in-app purchase",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "cost_per_in_app_purchase",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "level_complete_app",
      label: "Level complete (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "level_complete_app",
    },
    {
      id: "achievement_unlocked_app",
      label: "Achievement unlocked (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "achievement_unlocked_app",
    },
    {
      id: "login_app",
      label: "Login (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "login_app",
    },
    {
      id: "sign_up_app",
      label: "Sign up (app)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "sign_up_app",
    },
    {
      id: "cost_per_sign_up_app",
      label: "Cost per sign up (app)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "cost_per_sign_up_app",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "custom_app_event",
      label: "Custom app event",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "custom_app_event",
    },
    {
      id: "cost_per_purchase_app",
      label: "Cost per purchase (app)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "App",
      path: "cost_per_purchase_app",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → TikTok shop (expanded) ───────────────
    {
      id: "product_views_shop",
      label: "Product views (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "product_views_shop",
    },
    {
      id: "add_to_cart_shop",
      label: "Add to cart (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "add_to_cart_shop",
    },
    {
      id: "complete_payment_shop",
      label: "Complete payment (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "complete_payment_shop",
    },
    {
      id: "content_views_shop",
      label: "Content views (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "content_views_shop",
    },
    {
      id: "total_orders_shop",
      label: "Total orders (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "total_orders_shop",
    },
    {
      id: "total_buyers_shop",
      label: "Total buyers (shop)",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "total_buyers_shop",
    },
    {
      id: "cost_per_purchase_shop",
      label: "Cost per purchase (shop)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "cost_per_purchase_shop",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },
    {
      id: "cost_per_add_to_cart_shop",
      label: "Cost per add to cart (shop)",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "TikTok shop",
      path: "cost_per_add_to_cart_shop",
      invertDelta: true,
      agg: "weighted_avg",
      aggWeight: "spend",
    },

    // ─── Tracking → Conversions → Offline (expanded) ───────────────────
    {
      id: "offline_ad_to_purchase",
      label: "Offline ad-to-purchase",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "offline_ad_to_purchase",
    },
    {
      id: "offline_purchase_value",
      label: "Offline purchase value",
      format: "currency",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "offline_purchase_value",
    },
    {
      id: "offline_lead",
      label: "Offline lead",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "offline_lead",
    },
    {
      id: "offline_appointment",
      label: "Offline appointment",
      format: "number",
      tab: "tracking",
      category: "Conversions",
      group: "Offline",
      path: "offline_appointment",
    },

    // ─── Tracking → Attribution → Click windows ────────────────────────
    {
      id: "conversions_1d_click",
      label: "Conversions (1-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Click windows",
      path: "conversions_1d_click",
    },
    {
      id: "conversions_7d_click",
      label: "Conversions (7-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Click windows",
      path: "conversions_7d_click",
    },
    {
      id: "conversions_28d_click",
      label: "Conversions (28-day click)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Click windows",
      path: "conversions_28d_click",
    },

    // ─── Tracking → Attribution → Engaged-view windows ─────────────────
    {
      id: "conversions_1d_engaged_view",
      label: "Conversions (1-day engaged view)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Engaged-view windows",
      path: "conversions_1d_engaged_view",
    },
    {
      id: "conversions_7d_engaged_view",
      label: "Conversions (7-day engaged view)",
      format: "number",
      tab: "tracking",
      category: "Attribution",
      group: "Engaged-view windows",
      path: "conversions_7d_engaged_view",
    },
    {
      id: "click_engaged_view_split",
      label: "Click vs engaged-view split",
      hint: "click ÷ (click + EV)",
      format: "percent",
      tab: "tracking",
      category: "Attribution",
      group: "Engaged-view windows",
      path: "click_engaged_view_split",
      agg: "weighted_avg",
      aggWeight: "conversions",
    },

    // ─── Ad settings → Identity → Names & IDs (expanded) ───────────────
    {
      id: "advertiser_id",
      label: "Advertiser ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "advertiser_id",
    },
    {
      id: "advertiser_name",
      label: "Advertiser name",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "advertiser_name",
    },
    {
      id: "campaign_id",
      label: "Campaign ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "campaign_id",
      validLevels: ["campaign", "adset", "ad"],
    },
    {
      id: "adgroup_id",
      label: "Ad group ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "adset_id",
      validLevels: ["adset", "ad"],
    },
    {
      id: "ad_id",
      label: "Ad ID",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "ad_id",
      validLevels: ["ad"],
    },
    {
      id: "date",
      label: "Date",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "date",
    },
    {
      id: "hour",
      label: "Hour",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "hour",
    },
    {
      id: "day_of_week",
      label: "Day of week",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "day_of_week",
    },
    {
      id: "identity_type",
      label: "Identity type",
      hint: "BC_AUTH_TT vs CUSTOMIZED_USER",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "identity_type",
      validLevels: ["ad"],
    },
    {
      id: "image_mode",
      label: "Image mode",
      hint: "IN_FEED_VIDEO vs SPARK_AD",
      format: "text",
      tab: "ad_settings",
      category: "Identity",
      group: "Names & IDs",
      path: "image_mode",
      validLevels: ["ad"],
    },

    // ─── Ad settings → Schedule & budget → Budget ──────────────────────
    {
      id: "daily_budget",
      label: "Daily budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "daily_budget",
      validLevels: ["campaign", "adset"],
    },
    {
      id: "lifetime_budget",
      label: "Lifetime budget",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Budget",
      path: "lifetime_budget",
      validLevels: ["campaign", "adset"],
    },

    // ─── Ad settings → Schedule & budget → Bid & optimization ──────────
    {
      id: "bid_price",
      label: "Bid price",
      format: "currency",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bid & optimization",
      path: "bid_price",
      validLevels: ["adset"],
    },
    {
      id: "bid_strategy",
      label: "Bid strategy",
      hint: "LOWEST_COST / COST_CAP / MIN_ROAS / BID_CAP",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bid & optimization",
      path: "bid_strategy",
      validLevels: ["adset"],
    },
    {
      id: "optimization_goal",
      label: "Optimization goal",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bid & optimization",
      path: "optimization_goal",
      validLevels: ["adset"],
    },
    {
      id: "billing_event",
      label: "Billing event",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bid & optimization",
      path: "billing_event",
      validLevels: ["adset"],
    },
    {
      id: "pacing",
      label: "Pacing",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Bid & optimization",
      path: "pacing",
      validLevels: ["adset"],
    },

    // ─── Ad settings → Schedule & budget → Schedule ────────────────────
    {
      id: "schedule_start",
      label: "Schedule start",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "schedule_start",
    },
    {
      id: "schedule_end",
      label: "Schedule end",
      format: "text",
      tab: "ad_settings",
      category: "Schedule & budget",
      group: "Schedule",
      path: "schedule_end",
    },

    // ─── Advanced → Video → Plays (expanded) ───────────────────────────
    {
      id: "video_view_25_percent",
      label: "Video views 25%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_view_25_percent",
    },
    {
      id: "video_view_50_percent",
      label: "Video views 50%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_view_50_percent",
    },
    {
      id: "video_view_75_percent",
      label: "Video views 75%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_view_75_percent",
    },
    {
      id: "video_view_100_percent",
      label: "Video views 100%",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_view_100_percent",
    },
    {
      id: "video_views_6s_real",
      label: "6-sec views (engaged)",
      hint: "engaged-view threshold",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "video_views_6s_real",
    },
    {
      id: "avg_view_time_per_user",
      label: "Avg view time per user",
      format: "duration",
      tab: "advanced",
      category: "Video",
      group: "Plays",
      path: "avg_view_time_per_user",
      agg: "weighted_avg",
      aggWeight: "reach",
    },

    // ─── Advanced → Video → Hook & hold (expanded) ─────────────────────
    {
      id: "hook_score",
      label: "Hook score",
      hint: "TikTok creative-quality index",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hook_score",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "hold_score",
      label: "Hold score",
      hint: "post-hook retention quality index",
      format: "number",
      tab: "advanced",
      category: "Video",
      group: "Hook & hold",
      path: "hold_score",
      agg: "weighted_avg",
      aggWeight: "video_views_2s",
    },

    // ─── Advanced → Video → Retention (NEW group) ──────────────────────
    {
      id: "retention_q1",
      label: "Retention Q1 (0-25%)",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Retention",
      path: "retention_q1",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "retention_q2",
      label: "Retention Q2 (25-50%)",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Retention",
      path: "retention_q2",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "retention_q3",
      label: "Retention Q3 (50-75%)",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Retention",
      path: "retention_q3",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },
    {
      id: "retention_q4",
      label: "Retention Q4 (75-100%)",
      format: "percent",
      tab: "advanced",
      category: "Video",
      group: "Retention",
      path: "retention_q4",
      agg: "weighted_avg",
      aggWeight: "video_plays",
    },

    // ─── Advanced → Engagement → Interactions (expanded) ───────────────
    {
      id: "saves",
      label: "Saves",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "saves",
    },
    {
      id: "total_engagements",
      label: "Total engagements",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "total_engagements",
    },
    {
      id: "engagement_rate",
      label: "Engagement rate",
      format: "percent",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "engagement_rate",
      agg: "weighted_avg",
      aggWeight: "impressions",
    },
    {
      id: "post_replies",
      label: "Post replies",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "post_replies",
    },
    {
      id: "sticker_clicks",
      label: "Sticker clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "sticker_clicks",
    },
    {
      id: "link_in_bio_clicks",
      label: "Link-in-bio clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "link_in_bio_clicks",
    },
    {
      id: "music_disc_clicks",
      label: "Music disc clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "music_disc_clicks",
    },
    {
      id: "sound_uses",
      label: "Sound uses",
      hint: "creators who used this sound",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Interactions",
      path: "sound_uses",
    },

    // ─── Advanced → Engagement → Profile (expanded) ────────────────────
    {
      id: "profile_impressions",
      label: "Profile impressions",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "profile_impressions",
    },
    {
      id: "anchor_clicks",
      label: "Anchor clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "anchor_clicks",
    },
    {
      id: "anchor_conversions",
      label: "Anchor conversions",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "anchor_conversions",
    },
    {
      id: "brand_takeover_clicks",
      label: "Brand Takeover clicks",
      hint: "legacy",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "brand_takeover_clicks",
    },
    {
      id: "topview_clicks",
      label: "TopView clicks",
      format: "number",
      tab: "advanced",
      category: "Engagement",
      group: "Profile",
      path: "topview_clicks",
    },

    // ─── Advanced → Audience demographics (NEW group) ──────────────────
    {
      id: "top_country",
      label: "Top country",
      format: "text",
      tab: "advanced",
      category: "Audience demographics",
      group: "Top segments",
      path: "top_country",
    },
    {
      id: "top_region",
      label: "Top region",
      format: "text",
      tab: "advanced",
      category: "Audience demographics",
      group: "Top segments",
      path: "top_region",
    },
    {
      id: "top_age_band",
      label: "Top age band",
      format: "text",
      tab: "advanced",
      category: "Audience demographics",
      group: "Top segments",
      path: "top_age_band",
    },
    {
      id: "top_gender",
      label: "Top gender",
      format: "text",
      tab: "advanced",
      category: "Audience demographics",
      group: "Top segments",
      path: "top_gender",
    },

    // ─── Advanced → Spark Ads & creator (NEW group) ────────────────────
    {
      id: "creator_handle",
      label: "Creator handle",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Creator",
      path: "creator_handle",
      validLevels: ["ad"],
    },
    {
      id: "branded_content_tag",
      label: "Branded content",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Creator",
      path: "branded_content_tag",
      validLevels: ["ad"],
    },
    {
      id: "paid_partnership_flag",
      label: "Paid partnership",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Creator",
      path: "paid_partnership_flag",
      validLevels: ["ad"],
    },
    {
      id: "post_url",
      label: "Post URL",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Post & music",
      path: "post_url",
      validLevels: ["ad"],
    },
    {
      id: "original_post_id",
      label: "Original post ID",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Post & music",
      path: "original_post_id",
      validLevels: ["ad"],
    },
    {
      id: "days_since_post",
      label: "Days since post",
      format: "number",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Post & music",
      path: "days_since_post",
      validLevels: ["ad"],
    },
    {
      id: "music_id",
      label: "Music ID",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Post & music",
      path: "music_id",
      validLevels: ["ad"],
    },
    {
      id: "original_audio",
      label: "Original audio",
      format: "text",
      tab: "advanced",
      category: "Spark Ads & creator",
      group: "Post & music",
      path: "original_audio",
      validLevels: ["ad"],
    },
  ],
};
